#-*- coding: utf-8 -*-

{
	"name": "EVoting",
	"version": "1.0", 
	"depends": [
		'base',
	],
	"author": "Akhmad D. Sembiring [vitraining.com]",
	"category": "Utility",
	"website": "http://vitraining.com",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the EVoting module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
		"security/groups.xml",
		"security/ir.model.access.csv",
		"view/menu.xml",
		# "view/voter.xml",
		# "view/candidate.xml",
		"view/voting_session.xml",
		"view/vote_record.xml",
		"view/voting_result.xml",
		"report/voter.xml",
		"report/candidate.xml",
		"report/voting_session.xml",
		"report/vote_record.xml",
		"report/voting_result.xml",
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}