#-*- coding: utf-8 -*-

{
	"name": "EVoting Inherited",
	"version": "1.0", 
	"depends": [
		'base',
		'mail',
		'vit_election_app',
		'vit_election_api'
	],
	"author": "Akhmad D. Sembiring [vitraining.com]",
	"category": "Utility",
	"website": "http://vitraining.com",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the EVoting module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
		"data/sequence_vote_record.xml",
		"data/cron.xml",
		"view/candidate.xml",
		"view/voter.xml",
		"view/vote_record.xml",
		"view/voting_result.xml",
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}